databases:
  - name: fibreconnect-db
    plan: free

services:
  - type: web
    name: fibreconnect
    env: node
    plan: free
    buildCommand: |
      cd client
      npm ci
      npm run build
      cd ../server
      npm ci
      npm run build
    startCommand: cd server && npm start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fibreconnect-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
